name: Actualizar repositorios

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta cada dÃ­a a medianoche
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Obtener repositorios
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/user/repos?type=owner > public/repos.json

      - name: Commit y push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/repos.json
          git commit -m "Actualizar repos.json" || echo "No hay cambios"
          git push
